import {NextResponse} from "next/server";
type A={token?:string;chain?:string;address?:string;signal?:string;time?:string;price?:number;firstSeenAt?:string;firstSeenPrice?:number;score?:number};
type Outcome={token?:string;chain?:string;signal:string;firstSeenAt:string;firstPrice:number;score?:number;h1?:number;h6?:number;h24?:number};
function store(){return{base:process.env["kv_KV_REST_API_URL"]||process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_URL,token:process.env["kv_KV_REST_API_TOKEN"]||process.env.KV_REST_API_TOKEN||process.env.UPSTASH_REDIS_REST_TOKEN}}
async function redis(args:unknown[]){const{base,token}=store();if(!base||!token)return null;const r=await fetch(base,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(args)});return r.ok?r.json():null}
function groupSignal(s=""){return s.includes("Momentum")?"Momentum":s.includes("Volume spike")?"Volume spike":s.includes("Multiple")?"Multiple signals":s.includes("Risk")||s.includes("Crash")?"Risk / downside":"Emerging activity"}
function median(v:number[]){if(!v.length)return null;const x=[...v].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
function stat(vals:number[]){return{samples:vals.length,average:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,median:median(vals),positive:vals.length?vals.filter(v=>v>0).length/vals.length*100:null,sufficient:vals.length>=20}}
export async function GET(){const raw=await redis(["LRANGE","signalforge:history",0,299]);const seed:A[]=Array.isArray(raw?.result)?raw.result.flatMap((x:string)=>{try{return[JSON.parse(x) as A]}catch{return[]}}):[];const unique=new Map<string,A>();for(const a of seed)if(a.chain&&(a.address||a.token)){const k=`${a.chain}:${a.address||a.token}`;if(!unique.has(k))unique.set(k,a)}const outcomes:Outcome[]=[];for(const firstSeed of unique.values()){let scans:A[]=[];if(firstSeed.address){const d=await redis(["LRANGE",`signalforge:history:${firstSeed.chain}:${firstSeed.address}`,0,575]);scans=Array.isArray(d?.result)?d.result.flatMap((x:string)=>{try{return[JSON.parse(x) as A]}catch{return[]}}):[]}if(!scans.length)scans=seed.filter(x=>x.chain===firstSeed.chain&&((firstSeed.address&&x.address===firstSeed.address)||(!firstSeed.address&&x.token===firstSeed.token)));scans=scans.filter(x=>x.time&&typeof x.price==="number"&&(x.price||0)>0).sort((a,b)=>new Date(a.time||0).getTime()-new Date(b.time||0).getTime());if(!scans.length)continue;const first=scans[0],p0=first.firstSeenPrice||first.price||0,t0=new Date(first.firstSeenAt||first.time||0).getTime();if(!p0||!t0)continue;const item:Outcome={token:first.token,chain:first.chain,signal:groupSignal(first.signal),firstSeenAt:new Date(t0).toISOString(),firstPrice:p0,score:first.score};for(const [h,k] of [[60,"h1"],[360,"h6"],[1440,"h24"]] as const){const target=t0+h*60000,match=scans.find(x=>new Date(x.time||0).getTime()>=target);if(match?.price)item[k]=((match.price-p0)/p0)*100}outcomes.push(item)}const signals=[...new Set(outcomes.map(x=>x.signal))],bySignal=signals.map(signal=>{const xs=outcomes.filter(x=>x.signal===signal),pick=(k:"h1"|"h6"|"h24")=>stat(xs.map(x=>x[k]).filter((v):v is number=>typeof v==="number"));return{signal,count:xs.length,h1:pick("h1"),h6:pick("h6"),h24:pick("h24")}});return NextResponse.json({ok:true,total:outcomes.length,bySignal,outcomes:outcomes.slice(-50).reverse(),methodology:{primary:"dedicated contract history",fallback:"global history",minimumSample:20}})}
